### ISSUE TITLE
libdc1394-dev is not available for Ubuntu 18.04

### ISSUE THREAD

**Issue by YFly** [lagadic/visp_ros_coppeliasim#2]
Dear lagadic:
I am a Chinese college student. When I used this tutorial, I found that in section 1.1, ‘libdc1394-dev’ is not applicable to Ubuntu 18.04, and an error indicating that the software package cannot be located will be displayed.I found on packages.ubuntu.com that it only applies to versions above 20.04, and ‘libdc1394-22-dev’ can be applied to 18.04, should I use it?Looking forward to your reply，thank you！

**Comment by fspindle** [comment]
This project is deprecated and now part of https://github.com/lagadic/visp_ros
